export const category = [
  {
    id: 1,
    title: 'CSS',
    img1: '/css1.png',
    img2: '/css2.png',
    img3: '/css3.png',
    link: '/category/css',
  },
  {
    id: 2,
    title: 'Java/JS',
    img1: '/java1.png',
    img2: '/java2.png',
    img3: '/java3.png',
    link: '/category/java',
  },
  {
    id: 3,
    title: 'Database',
    img1: '/db1.png',
    img2: '/db2.png',
    img3: '/db3.png',
    link: '/category/database',
  },
  {
    id: 4,
    title: 'Python',
    img1: '/py1.png',
    img2: '/py2.png',
    img3: '/py3.png',
    link: '/category/python',
  },
  {
    id: 5,
    title: 'Cloud',
    img1: '/cloud1.png',
    img2: '/cloud2.png',
    img3: '/cloud3.png',
    link: '/category/cloud',
  },
  {
    id: 6,
    title: 'PHP',
    img1: '/php1.png',
    img2: '/php2.png',
    img3: '/php3.png',
    link: '/category/php',
  },
];

export const others = [
  {
    id: 1,
    title: 'Suspense',
    img1: '/sus1.jpeg',
    img2: '/sus2.jpeg',
    img3: '/sus3.jpeg',
    link: '/category/suspense',
  },
  {
    id: 2,
    title: 'Horror',
    img1: '/horror1.jpg',
    img2: '/horror2.jpg',
    img3: '/horror3.jpg',
    link: '/category/horror',
  },
  {
    id: 3,
    title: 'Drama',
    img1: '/drama1.jpg',
    img2: '/drama2.jpg',
    img3: '/drama3.jpg',
    link: '/category/drama',
  },
  {
    id: 4,
    title: 'Comedy',
    img1: '/comedy1.jpg',
    img2: '/comedy2.jpg',
    img3: '/comedy3.jpg',
    link: '/category/comedy',
  },
  {
    id: 5,
    title: 'Action',
    img1: '/action1.jpg',
    img2: '/action2.jpg',
    img3: '/action3.jpg',
    link: '/category/action',
  },
  {
    id: 6,
    title: 'Fiction',
    img1: '/fiction1.jpg',
    img2: '/fiction2.jpg',
    img3: '/fiction3.jpg',
    link: '/category/fiction',
  },
];
