export const category = [
  {
    id: 1,
    title: 'CSS',
    img1: '/css1.png',
    img2: '/css2.png',
    img3: '/css3.png',
    link: '/css',
  },
  {
    id: 2,
    title: 'Java/JS',
    img1: '/java1.png',
    img2: '/java2.png',
    img3: '/java3.png',
    link: '/java-js',
  },
  {
    id: 3,
    title: 'Database',
    img1: '/db1.png',
    img2: '/db2.png',
    img3: '/db3.png',
    link: '/database',
  },
  {
    id: 4,
    title: 'Python',
    img1: '/py1.png',
    img2: '/py2.png',
    img3: '/py3.png',
    link: '/python',
  },
  {
    id: 5,
    title: 'Cloud',
    img1: '/cloud1.png',
    img2: '/cloud2.png',
    img3: '/cloud3.png',
    link: '/cloud',
  },
  {
    id: 6,
    title: 'PHP',
    img1: '/php1.png',
    img2: '/php2.png',
    img3: '/php3.png',
    link: '/php',
  },
];
