import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { data } from "../data/data";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data.map((res) => (
          <div key={res.id} style={{ background: "yellow", width: "200px" }}>
            <p>{res.userId}</p>
            <p>{res.firstName}</p>
            <p>{res.email}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
