import Head from 'next/head';
import { useState, useEffect } from 'react';
import { gql, useQuery } from '@apollo/client';
import Header from '../src/components/common/Header';
import About from '../src/components/common/About';
import { signIn, getSession } from 'next-auth/react';
import { useRouter } from 'next/router';

const AllBooksQuery = gql`
  query {
    books {
      title
    }
  }
`;

export default function Home() {
  const router = useRouter();
  const session = getSession();
  console.log('sess ->>', session);

  //const { data, error, loading } = useQuery(AllBooksQuery);

  // if (loading) return <p>Loading....</p>;
  // if (error) return <p>Error, {error.message}</p>

  //console.log(data);

  // useEffect(() => {
  //   if (session) {
  //     router.push('/Home');
  //   }
  //   return;
  // }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <button
        onClick={() =>
          signIn('google', { callbackUrl: 'http://localhost:3000/Home' })
        }
      >
        Sign in
      </button>
      <Header />
      <About />
      {/* <div>
        {data?.books?.map((res) => (
          <div key={res.title}>
            <p>{res.title}</p>
          </div>
        ))}
      </div> */}
    </div>
  );
}

// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`https://api.itbook.store/1.0/new`);
//   const data = await res.json();

//   // console.dir(data, { depth: null });

//   // Pass data to the page via props
//   return { props: { data } };
// }
