import Head from 'next/head';
import { useState, useEffect, useContext } from 'react';
import { useRouter } from 'next/router';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { ViewContext } from '../pages/_app';

export default function Home() {
  const [viewContext, setViewContext] = useContext(ViewContext);
  const { getUserItem, getItem } = useLocalStorage({});
  const router = useRouter();

  useEffect(() => {
    const loggedInUser = getUserItem({ key: 'user' });
    if (loggedInUser) {
      router.push('/Home');
    } else {
      router.push('/account/login');
    }
  }, []);

  //console.log('st -->', token);

  return (
    <div>
      <Head>
        <title>E-Books Online Library</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
}
